services:
  - type: web
    name: lms-platform
    runtime: node
    plan: free
    buildCommand: node scripts/switch-to-pg.js && npm install --include=dev && npx prisma generate && npx prisma db push --skip-generate && npx prisma db seed && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lms-database
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://lms-platform.onrender.com"
      - key: AUTH_TRUSTED_HOST
        value: "lms-platform.onrender.com"

databases:
  - name: lms-database
    plan: free
    databaseName: lms
    user: lms_user
